### PR TITLE
Update to 0.3.19

### PR DESCRIPTION
**Pull request by jschueller**
@conda-forge-admin please rerender

### CODE REVIEW

**Comment by jschueller** [comment]
@conda-forge-admin please rerender

**Comment by jschueller** [comment]
I think its ready to go @t-sommer

**Review by t-sommer — CHANGES_REQUESTED** [review]
If you install from source you're missing all the binaries that come with the wheel.
You will also have to replicate the build and merge jobs in https://github.com/CATIA-Systems/FMPy/blob/main/azure-pipelines.yml.

**Comment by jschueller** [comment]
> If you install from source you're missing all the binaries that come with the wheel. You will also have to replicate the build and merge jobs in https://github.com/CATIA-Systems/FMPy/blob/main/azure-pipelines.yml.

indeed, lets stick to the wheel for now, but I posted a patch to allow building with recent sundials though

**Comment by jschueller** [comment]
@conda-forge-admin please rerender

**Comment by jschueller** [comment]
@t-sommer this should be good to go now, could you have a look ?

**Comment by t-sommer** [comment]
Superseded by #64.

**Pull request closed without merging**
